services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - lms-network
    depends_on:
      - db
    ports:
      - "8000:80"

  db:
    image: mysql:8.0
    container_name: lms-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: lms_database
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: user_password
      MYSQL_USER: lms_user
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - lms-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lms-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8082:80"
    networks:
      - lms-network
    depends_on:
      - db

volumes:
  dbdata:
    driver: local

networks:
  lms-network:
    driver: bridge